### ISSUE TITLE
Focus claimed after each interaction with the page

### ISSUE THREAD

**Issue by lucach** [LuCEresearchlab/react-expression-tree#63]
The canvas claims the focus after each interaction with the page it is embedded in (e.g., typing in an input field).

I suspect that continuously claiming the focus

https://github.com/LuCEresearchlab/react-expression-tree/blob/6836bb2375fa1c3eaf83b5f78835e633bb8d8a08/src/components/ExpressionTreeEditor/ExpressionTreeEditor.jsx#L293-L296

is unnecessary: we only want to react to keyboard events when the component already has the focus.

**Comment by thefooly** [comment]
I did not test this issue yet, but I agree that line 296 should be improved.
Probably we want to create a new flag `isSelected`, which is set to `true` when the component is clicked. 
Keypress events will work only when the flag is `true`.

## Question:
Can users press keys if `isSelected` is `false`, but they are hovering the mouse on the component? 
I believe that in some cases this is a needed behavior, but it is not in Expression Tutor. If there is a selected input in the page, there will be issues.

Maybe we should also create a configurable property `allowSelectedOnHover` which allows the component to automatically be selected when the mouse hovers on the component.

**Comment by lucach** [comment]
I don't think that anybody expects that hovering something (without clicking) grabs the focus. That's just not how users are used to UIs. I'd just fix the issue by removing the annoying behavior for now, and only later if we have time add yet another config.

**Comment by lucach** [comment]
Fixed in b1c2ecc567bcf9b79bed1c2904e9cec64861e388
