### ISSUE TITLE
Placeholder texts for types and values are language specific

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/react-expression-tree#78]
Right now the placeholder text in the empty type and value textfields suggest types and values that are ok in JavaScript but can be wrong in other languages (including the actual language of the activity).

Either remove the placeholder, or make it so that it's correct in most languages (e.g., use double-quotes for string values), or make it configurable and pass the corresponding language-specific props from the surrounding activities.

**Comment by thefooly** [comment]
This is not an issue of react-expression-tree, but of Expression Tutor. Placeholder types and values are editable
